<a href="https://colab.research.google.com/github/Melo987/-v2/blob/main/%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C%E5%AE%9E%E7%8E%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [5]:
# 张量表示一个数值组成的数组，这个数组可能有多个维度
x = torch.arange(12)
x # jupyter写法，后默认为第一行为jupyter写法
print(x) # py写法，后默认第二行为py写法


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [8]:
# 可以通过shape属性访问张量的形状和张量元素中元素的总数
x.shape
print(x.shape)


torch.Size([12])


In [12]:
x.numel()
print(x.numel())


12


In [14]:
# 改变张量的形状而不改变元素数量和元素值，可以调用reshape函数
# x = x.reshape(3,4)
# x

x=x.reshape(3,4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [20]:
# 使用全0、全1、其他常量或者从特地给分不中随机采样的数字
torch.zeros(2,3,4)
torch.ones(1,2,3)
torch.randn(2,3,4)

y=torch.zeros(2,3,4)
z=torch.ones(1,2,3)
u=torch.randn(2,3,4)
print(y,z,u)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) tensor([[[1., 1., 1.],
         [1., 1., 1.]]]) tensor([[[-0.4310,  0.1812, -0.4377,  0.7276],
         [ 0.6530,  1.0973,  0.6233,  1.8448],
         [ 0.7096,  0.9681,  0.1419,  0.0351]],

        [[-0.3618,  0.2032, -1.7601, -0.2539],
         [ 0.0267,  0.9878, -0.0237,  1.3831],
         [ 0.9830, -1.0045,  0.9861,  1.4473]]])


In [22]:
# 通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值
torch.tensor([[1,2,3,4],[1,2,4,3],[4,3,2,1]])
q=torch.tensor([[1,2,3,4],[1,2,4,3],[4,3,2,1]])
print(q)

tensor([[1, 2, 3, 4],
        [1, 2, 4, 3],
        [4, 3, 2, 1]])
