<a href="https://colab.research.google.com/github/Melo987/-v2/blob/main/%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C%E5%AE%9E%E7%8E%B0%E4%B8%8E%E6%95%B0%E6%8D%AE%E9%A2%84%E5%A4%84%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
# 张量表示一个数值组成的数组，这个数组可能有多个维度
x = torch.arange(12)
x # jupyter写法，后默认为第一行为jupyter写法
print(x) # py写法，后默认第二行为py写法


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [ ]:
# 可以通过shape属性访问张量的形状和张量元素中元素的总数
x.shape
print(x.shape)


torch.Size([12])


In [ ]:
x.numel()
print(x.numel())


12


In [ ]:
# 改变张量的形状而不改变元素数量和元素值，可以调用reshape函数
# x = x.reshape(3,4)
# x

x=x.reshape(3,4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
# 使用全0、全1、其他常量或者从特地给分不中随机采样的数字
torch.zeros(2,3,4)
torch.ones(1,2,3)
torch.randn(2,3,4)

y=torch.zeros(2,3,4)
z=torch.ones(1,2,3)
u=torch.randn(2,3,4)
print(y,z,u)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) tensor([[[1., 1., 1.],
         [1., 1., 1.]]]) tensor([[[-0.4310,  0.1812, -0.4377,  0.7276],
         [ 0.6530,  1.0973,  0.6233,  1.8448],
         [ 0.7096,  0.9681,  0.1419,  0.0351]],

        [[-0.3618,  0.2032, -1.7601, -0.2539],
         [ 0.0267,  0.9878, -0.0237,  1.3831],
         [ 0.9830, -1.0045,  0.9861,  1.4473]]])


In [ ]:
# 通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值
torch.tensor([[1,2,3,4],[1,2,4,3],[4,3,2,1]])
q=torch.tensor([[1,2,3,4],[1,2,4,3],[4,3,2,1]])  #二维

print(q.shape) 

torch.Size([3, 4])


In [ ]:
# 常见的标准算术运算符+ - * / ** 都可以升级为按元素计算
x = torch.tensor([1.0,2,4,8])   # 1.0为浮点数，其余为整数
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y



(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
# 把多个张量连结在一起
X = torch.arange(12, dtype=torch.float32).reshape((3,4))  #float生成浮点数
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)  # dim=0表示按行相加，dim=1表示按列
#连结concatenate，将他们端到端堆叠以形成更大的张量
#dim维数，第一层括号代表第0维

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
# 通过逻辑运算符构建二元张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# 对张量中所有元素进行求和会产生一个只有一个元素的张量，即标量
X.sum()

tensor(66.)

In [ ]:
# 即使形状不同，仍然可以通过调用广播机制（broadcasting mechanism）来执行按元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# 可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素
X[-1],X[1:3],X[1:3,1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]), tensor([[ 5.,  6.],
         [ 9., 10.]]))

In [ ]:
# 通过指定索引将元素写入矩阵
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 为多个元素赋相同的值，索引所有元素，赋值
X[0:2, : ]=11
X

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 节省内存
before = id(Y)   # id()函数提供了内存中引用对象的确切位置
Y = Y + X
id(Y) == before   # python首先计算Y+X，为结果分配新的内存，然后使Y指向内存中的这个新位置

False

In [ ]:
# 执行原地操作
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z)) # 如果后续计算中没有重复使用X，可以使用X[:]=X+Y或X+=Y来减少操作的内存的开销

before = id(X)
X += Y
id(X) == before

id(Z): 139871765991504
id(Z): 139871765991504


True

In [ ]:
# 转换为NumPy张量
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
# 将大小为1d张量转换为python标量
a = torch.tensor(3.5)
a,a.item(),float(a),int(a)   # item、float都表示浮点数

(tensor(3.5000), 3.5, 3.5, 3)

In [ ]:
# 数据预处理

In [ ]:
# 创建一个人工数据集，并存储在csv（都好分隔值）文件
import os 

os.makedirs(os.path.join('..','data'),exist_ok=True)  
#os.makerdirs(path)创建目录
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
  f.write('NumRooms,Alley,Price\n')  # 列名
  f.write('NA,Pave,127500\n')  # 每行表示一个数据样本  NA表示未知的数
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')


os.mkdir(path)，他的功能是一级一级的创建目录，前提是前面的目录已存在，如果不存在会报异常，比较麻烦，但是存在即有他的道理，当你的目录是根据文件名动态创建的时候，你会发现他虽然繁琐但是很有保障，不会因为你的一时手抖，创建而创建了双层或者多层错误路径，

os.makedirs(path),单从写法上就能猜出他的区别，他可以一次创建多级目录，哪怕中间目录不存在也能正常的（替你）创建，想想都可怕，万一你中间目录写错一个单词

In [ ]:
# 从创建的csv文件中加载原始数据集
import pandas as pd     # 用pandas读取csv文件

data = pd.read_csv(data_file)
# print(data)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [ ]:
# 为了处理缺失的数据，典型的方法包括插值和删除，这里考虑插值
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())  #mean()均值
#fillna对所有未知的值NaN填入一个值
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
# 对于inputs中的类别值或离散值，我们将NaN视为一个类别
inputs = pd.get_dummies(inputs,dummy_na=True)
#pd.get_dummies()将alley的值转换成两类
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [ ]:
# 现在inputs和outputs中的所有条目都是数值类型，它们可以转换为张量格式
import torch
x,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))