<a href="https://colab.research.google.com/github/Melo987/-v2/blob/main/%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 线性代数

In [2]:
import torch

In [ ]:
# 标量由只有一个元素的张量表示
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x+y,x-y,x*y,x/y,x**y

(tensor([5.]), tensor([1.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [ ]:
# 可以将向量视为标量值组成的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
# 通过张量的索引来访问任意元素
x[3]

tensor(3)

In [ ]:
# 访问张量的长度
len(x)

4

In [3]:
v = torch.arange(24).reshape(2,3,4)
len(v)   # 三维张量的长度

2

In [ ]:
# 只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

In [ ]:
# 通过指定两个分量m和n来创建一个形状为m*n的矩阵
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [ ]:
# 对称矩阵 A等于其转置：A=A.T
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [ ]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
# 向量是标量的推广，矩阵是向量的推广，可以构建具有更多轴的数据结构
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
# 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都是相同形状的张量
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()  # 通过分配新内存，将A 的一个副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [ ]:
# 两个矩阵的按元素乘法称为  哈达玛积
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [ ]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X,(a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

In [ ]:
# 计算其元素的和
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [ ]:
# 表示任意形状张量的元素和
A = torch.arange(20).reshape(5,4)
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190))

In [ ]:
# 指定求和汇总张量的轴 
A_sum_axis0 = A.sum(axis=0)   # axis=0 0轴，按列求和
A_sum_axis0,A_sum_axis0.shape

(tensor([40, 45, 50, 55]), torch.Size([4]))

In [ ]:
A_sum_axis1 = A.sum(axis=1)    # 按行求和
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6, 22, 38, 54, 70]), torch.Size([5]))

In [4]:
B = torch.arange(40).reshape(2,5,4)
B

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [ ]:
B_sum_axis0 = B.sum(axis=0)   #按二维的元素求和，即两个矩阵对应位置元素求和
B_sum_axis0,B_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]), torch.Size([5, 4]))

In [ ]:
B_sum_axis1 = B.sum(axis=1)   # 两个矩阵分别分别按列求和，结果是二维
B_sum_axis1,B_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]), torch.Size([2, 4]))

In [ ]:
B.sum(axis=[0,1]),B.sum(axis=[0,1]).shape   #两个矩阵按列求和

(tensor([180, 190, 200, 210]), torch.Size([4]))

In [ ]:
B.sum(axis=[1,2]),B.sum(axis=[1,2]).shape  # (5,4)求和，即两个矩阵分别求和

(tensor([190, 590]), torch.Size([2]))

In [5]:
# 一个与求和相关的量是 平均值 （mean或average）
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.mean(),A.sum()/A.numel(),A.numel()

(tensor(9.5000), tensor(9.5000), 20)

In [ ]:
A.mean(axis=0),A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [ ]:
# 计算总和或均值时保持轴数不变
sum_A = A.sum(axis=1,keepdims=True)
sum_A,sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]), torch.Size([5, 1]))

In [ ]:
# 可以理解为，axis=几，将该轴元素求和，结果维度取消这一轴
# 例如shape[5,4]，axis=0即第0轴，结果维度为[4]   shape[2,5,4],axis=[0,1]，结果维度为[4]
# keepdims = True 可以保留该轴为1，例如  shape[2,5,4],axis=[0,1]，keepdims=True,  维度为[1,1,4]

In [ ]:
# 通过广播将A除以sum_A
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [ ]:
# 某个轴计算A元素的累计总和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [ ]:
# 点积是相同位置的按元素乘积的和
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [ ]:
# 可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x*y)

tensor(6.)

In [ ]:
# 矩阵向量积Ax是一个长度为m的列向量
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [ ]:
# 可以将矩阵-矩阵乘法AB看作是简单执行m次矩阵向量积，并将结果拼接在一起，形成一个n*mjuzhen
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [ ]:
# 二范数是向量元素平方和的平方根
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [ ]:
# 一范数，向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [ ]:
# 矩阵的F范数，矩阵元素平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)

In [9]:
# 根据索引访问矩阵
y = torch.arange(10).reshape(5,2)
index = torch.tensor([1,4])
y[index]

tensor([[2, 3],
        [8, 9]])

In [4]:
# 理解pytorch中的gather()函数
a = torch.arange(15).view(3,5)
a

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [5]:
# 二维矩阵上gather()函数
b = torch.zeros_like(a)
b[1][2] = 1
b[0][0] = 1
b

tensor([[1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0]])

In [6]:
c = a.gather(0,b)  # dim=0   b相当于index索引，dim=0，即对0轴做出改变，a，b，
#                   c分别对应
d = a.gather(1,b)  # dim=1
c,d

(tensor([[5, 1, 2, 3, 4],
         [0, 1, 7, 3, 4],
         [0, 1, 2, 3, 4]]), tensor([[ 1,  0,  0,  0,  0],
         [ 5,  5,  6,  5,  5],
         [10, 10, 10, 10, 10]]))

In [7]:
#三维矩阵上gather()函数
a = torch.randint(0,30,(2,3,5))  # randint（）随机分布
a

tensor([[[22, 29, 11, 18,  2],
         [23, 14, 14, 13, 29],
         [25,  7, 17, 29, 29]],

        [[ 7, 19, 22, 11, 19],
         [25, 24,  6, 19,  1],
         [12, 14,  3, 29, 22]]])

In [8]:
index = torch.LongTensor([[[0,1,2,0,2],[0,0,0,0,0],[1,1,1,1,1]],[[1,2,2,2,2],[0,0,0,0,0],[2,2,2,2,2]]])
index

tensor([[[0, 1, 2, 0, 2],
         [0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1]],

        [[1, 2, 2, 2, 2],
         [0, 0, 0, 0, 0],
         [2, 2, 2, 2, 2]]])

In [9]:
b = torch.gather(a,1,index)
b

tensor([[[22, 14, 17, 18, 29],
         [22, 29, 11, 18,  2],
         [23, 14, 14, 13, 29]],

        [[25, 14,  3, 29, 22],
         [ 7, 19, 22, 11, 19],
         [12, 14,  3, 29, 22]]])

In [16]:
a = torch.arange(30).reshape(2,3,5)
a

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

In [17]:
c = torch.gather(a,2,index)
c

tensor([[[ 0,  1,  2,  0,  2],
         [ 5,  5,  5,  5,  5],
         [11, 11, 11, 11, 11]],

        [[16, 17, 17, 17, 17],
         [20, 20, 20, 20, 20],
         [27, 27, 27, 27, 27]]])

In [22]:
# 理解pytorch中的max()和argmax()函数
a = torch.tensor([[1,2,3],[3,2,1]])
a,a.shape

(tensor([[1, 2, 3],
         [3, 2, 1]]), torch.Size([2, 3]))

In [20]:
a.argmax(1)   # argmax()表示寻找最大评分的参量   1表示dim=1

tensor([2, 0])

In [21]:
a.max(1)

torch.return_types.max(values=tensor([3, 3]), indices=tensor([2, 0]))

In [32]:
a.max(1)[1],a.max(1)[0]

(tensor([2, 0]), tensor([3, 3]))

In [24]:
a.argmax(0)

tensor([1, 0, 0])

In [29]:
b = torch.tensor([[[1,2,3],[2,3,4]],[[3,5,1],[1,6,8]]])
b,b.shape

(tensor([[[1, 2, 3],
          [2, 3, 4]],
 
         [[3, 5, 1],
          [1, 6, 8]]]), torch.Size([2, 2, 3]))

In [28]:
b.argmax(1)

tensor([[1, 1, 1],
        [0, 1, 1]])

In [30]:
b.argmax(2)

tensor([[2, 2],
        [1, 2]])

In [31]:
b.max(1)

torch.return_types.max(values=tensor([[2, 3, 4],
        [3, 6, 8]]), indices=tensor([[1, 1, 1],
        [0, 1, 1]]))

In [33]:
b.argmax(0)

tensor([[1, 1, 0],
        [0, 1, 1]])

In [34]:
b.max(0)

torch.return_types.max(values=tensor([[3, 5, 3],
        [2, 6, 8]]), indices=tensor([[1, 1, 0],
        [0, 1, 1]]))

In [35]:
# item()函数
a = torch.Tensor([1, 2, 3])
print('a[0]:', a[0])  # 直接取索引返回的是tensor数据
print('a[0].item():', a[0].item()) 

a[0]: tensor(1.)
a[0].item(): 1.0


# 06 **矩阵计算**

In [ ]:
# 标量导数
# torch中默认log是以e为底的
